name: SCANOSS Int Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  scanoss-code-scan:
    name: SCANOSS Code Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SCANOSS Code Scan
        id: scanoss-code-scan-step
        uses: scanoss/code-scan-action@v1.2.4

        with:
          dependencies.enabled: true
          policies: und, dt
          api.key: ${{ secrets.SC_API_KEY }}
          deptrack.upload: false
          deptrack.url: 'https://dependency-track.scanoss.xyz/'
          deptrack.projectname: 'alex-test'
          deptrack.projectversion: '1.0.0'
          deptrack.apikey: ${{ secrets.SC_DT_API_KEY }}
